# tasks for postfix
- name: Install Postfix
  apt:
    name: [postfix, postfix-mysql]
    state: present

- name: Deploy main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
  notify: Restart postfix

- name: Ensure postfix is running
  service:
    name: postfix
    state: started
    enabled: yes
