#SPDX-License-Identifier: MIT-0
---
# tasks file for proxmox_create_container
# - name: install proxmoxer and requests on the host
#   shell:
#     cmd: pip3 install -U proxmoxer requests
- name: Install pip3 and proxmoxer
  apt:
    name:
      - python3-pip
      - python3-proxmoxer
      - python3-requests
    state: present

- name: Create LXC container
  community.general.proxmox:
    api_user: root@pam
    api_password: "{{ host_api_passwd }}"
    api_host: localhost
    vmid: "{{ container_id }}"
    password: "{{ container_passwd }}"
    node: "{{ host_nodename }}"
    hostname: "{{ container_name }}"
    ostemplate: "{{ container_template }}"
    searchdomain: "{{ container_search_domain }}"
    memory: "{{ container_memory }}"
    cores: "{{ container_cores }}"
    pubkey: "{{ container_pubkey }}"
    description: "created with ansible"
    disk_volume:
      storage: "{{ container_rootfs_storage }}"
      size: "{{ container_rootfs_storage_size }}"
    mount_volumes:
      - id: mp0
        storage: "{{ container_mount_storage }}"
        size: "{{ container_mount_storage_size }}"
        mountpoint: "{{ container_mount_point }}"
    netif:
      net0: "name=eth0,bridge=vmbr0,ip=dhcp,firewall=1"
    state: present
    features:
      - nesting=1
      # - mount=cifs,nfs
    validate_certs: false

- name: Start LXC container
  community.general.proxmox:
    api_user: root@pam
    api_password: "{{ host_api_passwd }}"
    api_host: localhost
    node: "{{ host_nodename }}"
    vmid: "{{ container_id }}"
    state: started
    validate_certs: false

- name: Get LXC container IP
  shell:
    cmd: pct exec {{ container_id }} -- ip -4 addr show eth0
  register: lxc_ip_result
  changed_when: false

- name: Prepare LXC container
  shell:
    cmd: pct exec {{ container_id }} -- bash -c "apt install -y openssh-server"

- name: Enable SSH in container
  shell:
    cmd: pct exec {{ container_id }} -- bash -c "systemctl enable --now ssh"

- name: Set IP fact
  set_fact:
    lxc_ip: "{{ lxc_ip_result.stdout | regex_search('inet ([0-9.]+)', '\\1') }}"

- name: Add container to inventory
  add_host:
    hostname: "{{ container_name }}.{{ container_search_domain }}"
    groups: "{{ container_name }}"
    ansible_host: "{{ lxc_ip[0] }}"
    ansible_user: root
