# tasks for roundcube
- name: Download Roundcube
  get_url:
    url: https://github.com/roundcube/roundcubemail/releases/download/1.6.7/roundcubemail-1.6.7-complete.tar.gz
    dest: /tmp/roundcube.tar.gz

- name: Extract Roundcube
  unarchive:
    src: /tmp/roundcube.tar.gz
    dest: /var/www/
    remote_src: yes

- name: Configure Roundcube
  template:
    src: config.inc.php.j2
    dest: /var/www/roundcube/config/config.inc.php
